import type { EmployeeRoleTemplate } from "../../types/employee";

export const PAPER_ROLES: EmployeeRoleTemplate[] = [
  {
    id: "production-worker",
    title: "Production Worker",
    department: "production",
    tier: 1,
    salaryRange: [32_000, 42_000],
    description: "Feeds and tends the converting line, packs finished cases, handles material movement on the floor.",
    delegates: "Manual production work you'd otherwise have to do yourself to keep the line running.",
  },
  {
    id: "machine-operator",
    title: "Machine Operator",
    department: "production",
    tier: 1,
    salaryRange: [38_000, 52_000],
    description: "Runs the converting/cutting equipment directly — skill here drives both output rate and scrap rate.",
    delegates: "Skilled machine operation; without one, a production worker runs equipment less efficiently.",
  },
  {
    id: "maintenance-tech",
    title: "Maintenance Technician",
    department: "maintenance",
    tier: 1,
    salaryRange: [42_000, 58_000],
    description: "Services the equipment on a schedule instead of only after it breaks, slowing condition decay and shortening downtime when it does.",
    delegates: "Preventive maintenance — without this role, equipment condition degrades faster and breakdowns last longer.",
  },
  {
    id: "quality-inspector",
    title: "Quality Inspector",
    department: "quality",
    tier: 1,
    salaryRange: [36_000, 48_000],
    description: "Catches defective output before it reaches a customer, reducing scrap loss and complaint-driven churn.",
    delegates: "Outgoing quality checks — without one, more defects reach customers.",
  },
  {
    id: "purchasing-agent",
    title: "Purchasing Agent",
    department: "purchasing",
    tier: 1,
    salaryRange: [38_000, 55_000],
    description: "Negotiates with pulp suppliers, times orders, and manages raw-material inventory levels.",
    delegates: "The buying decisions you're currently making yourself every week.",
  },
  {
    id: "sales-rep",
    title: "Sales Representative",
    department: "sales",
    tier: 1,
    salaryRange: [40_000, 60_000],
    description: "Maintains existing distributor/print-shop relationships and pursues new accounts.",
    delegates: "Prospecting and account management you're currently handling yourself.",
  },
  {
    id: "bookkeeper",
    title: "Bookkeeper",
    department: "accounting",
    tier: 1,
    salaryRange: [38_000, 52_000],
    description: "Handles day-to-day transaction recording, invoicing, and bill payment.",
    delegates: "The bookkeeping you're currently doing yourself, including the error risk of doing it in spare time.",
  },
  {
    id: "plant-manager",
    title: "Plant Manager",
    department: "management",
    managesDepartment: "production",
    tier: 2,
    salaryRange: [65_000, 90_000],
    description: "Runs the production floor day-to-day — oversees production, maintenance, and quality staff and lifts their overall effectiveness.",
    delegates: "Direct oversight of the entire production floor, freeing you from daily plant supervision.",
  },
  {
    id: "controller",
    title: "Controller",
    department: "management",
    managesDepartment: "accounting",
    tier: 2,
    salaryRange: [70_000, 95_000],
    description: "Owns the full accounting function and financial reporting, supervising bookkeeping staff.",
    delegates: "Financial oversight and reporting — the last piece of accounting you'd otherwise touch personally.",
  },
  {
    id: "sales-manager",
    title: "Sales Manager",
    department: "management",
    managesDepartment: "sales",
    tier: 2,
    salaryRange: [68_000, 92_000],
    description: "Runs the sales function — sets territory/account priorities for reps and is accountable for the team's overall performance.",
    delegates: "Day-to-day sales management, freeing you from directing account strategy yourself.",
  },
  {
    id: "purchasing-manager",
    title: "Purchasing Manager",
    department: "management",
    managesDepartment: "purchasing",
    tier: 2,
    salaryRange: [66_000, 90_000],
    description: "Owns supplier strategy — negotiates larger contracts and directs purchasing agents.",
    delegates: "Supplier strategy and negotiation oversight, beyond what a single purchasing agent handles alone.",
  },
];

export const PAPER_ROLES_BY_ID: Record<string, EmployeeRoleTemplate> = Object.fromEntries(
  PAPER_ROLES.map((r) => [r.id, r]),
);
